version: '3.7'

services:
    postgres:
        container_name: postgres
        build:
            context: docker/postgres
            dockerfile: Dockerfile
        environment:
            - POSTGRES_PASSWORD=testpass
        volumes:
            - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
        expose:
            - "5432"

    web:
        container_name: web
        build:
            context: deploy/
            dockerfile: Dockerfile
        volumes:
            - ./:/usr/src/app
        entrypoint: /usr/src/app/deploy/entrypoint.sh
        depends_on:
            - postgres
            - celery-worker

    nginx:
        container_name: nginx
        build:
            context: docker/nginx
            dockerfile: Dockerfile
        depends_on:
            - web
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - ./static/:/static/
            - ./media/:/media/
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot

    certbot:
        container_name: certbot
        image: certbot/certbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot

    redis:
        container_name: redis
        image: "redis:alpine"
        expose:
            - "6379"
        restart: always

    celery-worker:
        container_name: celery-worker
        restart: always
        build:
            context: deploy
            dockerfile: Dockerfile
        entrypoint: /usr/src/app/deploy/celeryworker.sh
        volumes:
            - ./:/usr/src/app
        depends_on:
            - redis

    celery-beat:
        container_name: celery-beat
        restart: always
        build:
            context: deploy
            dockerfile: Dockerfile
        entrypoint: /usr/src/app/deploy/celerybeat.sh
        volumes:
            - ./:/usr/src/app
        depends_on:
            - redis
            - celery-worker

    flower:
        container_name: flower
        restart: always
        build:
            context: deploy
            dockerfile: Dockerfile
        entrypoint: /usr/src/app/deploy/flower.sh
        volumes:
            - ./:/usr/src/app
        ports:
            - "5555:5555"
        depends_on:
            - celery-worker